#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDC_MSGINFO_ICON                        2000
#define IDC_MSG                                 2001
#define IDC_WRENCH                              2002
#define IDC_BOOKMARK_PLUS                       2003
#define IDC_LABELSET                            2004
#define IDC_LISTVIEW                            2005
#define IDC_RA_INPUT                            3000
#define IDC_RA_ANALYSE                          3001
#define IDC_RA_REGIST                           3002
#define IDC_RA_CHECK                            3003
#define IDC_RA_MSG                              3004
#define IDC_RS_MSG                              4000
#define IDC_RS_EDIT_KEY                         4001
#define IDC_RS_EDIT_KEYNAME                     4002
#define IDC_RS_CB_KEYNAME                       4003
#define IDC_RS_KEYNAME_ACQ                      4004
#define IDC_RS_EDIT_MEMO                        4005
#define IDC_RS_CB_MEMO                          4006
#define IDC_RS_CHECK_BALLOON                    4007
#define IDC_RS_CHECK_BROWSER                    4008
#define IDC_RS_CHECK_SOUND                      4009
#define IDC_RS_CHECK_EXTAPP                     4010
#define IDC_RS_SAVE                             4011
#define IDC_SE_MINIMIZE_ON_CLOSE                5000
#define IDC_SE_CONFIRM_ON_CLOSE                 5001
#define IDC_SE_MINIMIZE_TO_TRAY                 5002
#define IDC_SE_MINIMIZE_ON_BOOT                 5003
#define IDC_SE_BALLOON_OPEN                     5004
#define IDC_SE_BALLOON_BOUYOMI                  5005
#define IDC_SE_AUTO_KEYNAME_ACQ                 5006
#define IDC_SE_TOOLTIP_HELP                     5007
#define IDC_SE_VERSION_CHECK                    5008
#define IDC_SE_SORT_COLOR_TX                    5010
#define IDC_SE_SORT_COLOR_BG                    5011
#define IDC_SE_BC_COLOR_TX                      5012
#define IDC_SE_BC_COLOR_BG                      5013
#define IDC_SE_CHECK_BALLOON                    5020
#define IDC_SE_CHECK_BROWSER                    5021
#define IDC_SE_CHECK_SOUND                      5022
#define IDC_SE_CHECK_EXTAPP                     5023
#define IDC_SE_DEFAULT_BROWSER_USE              5030
#define IDC_SE_BROWSER_PATH                     5031
#define IDC_SE_BROWSER_REF                      5032
#define IDC_SE_SOUND_PATH                       5033
#define IDC_SE_SOUND_REF                        5034
#define IDC_SE_SOUND_VOL                        5035
#define IDC_SE_SOUND_PLAY                       5036
#define IDC_SE_EXTAPP_PATH                      5037
#define IDC_SE_EXTAPP_REF                       5038
#define IDC_SE_CANCEL                           5040
#define IDC_SE_SAVE                             5041
#define IDC_SE_ITEM_DC_ENABLE                   5050
#define IDC_SE_ITEM_DC_ITEMSETTING              5051
#define IDC_SE_ITEM_DC_OPEN_LV                  5052
#define IDC_SE_ITEM_DC_OPEN_ID                  5053
#define IDC_SE_POPUP_ENABLE                     5060
#define IDC_SE_POPUP_LEFTTOP                    5061
#define IDC_SE_POPUP_LEFTBOTTOM                 5062
#define IDC_SE_POPUP_RIGHTTOP                   5063
#define IDC_SE_POPUP_RIGHTBOTTOM                5064
#define IDC_MI_MSG                              6000
#define IDC_LS_LISTVIEW                         7000
#define IDC_LS_LABELSET                         7001
#define IDC_LS_LABELUNSET                       7002
#define IDC_LS_LABELFILTER                      7003
#define IDC_LS_CLEARFILTER                      7004
#define IDM_ALLSEL                              40000
#define IDM_SETTING                             40001
#define IDM_REGADD                              40002
#define IDM_REGSET                              40003
#define IDM_REGDEL                              40004
#define IDM_ENABLE                              40005
#define IDM_DISABLE                             40006
#define IDM_RESTORE                             40007
#define IDM_EXIT                                40008
#define IDM_OPEN_CO                             40009
#define IDM_OPEN_CH                             40010
#define IDM_OPEN_USER                           40011
#define IDM_OPEN_LV                             40012
#define IDM_OPEN_LV_CB                          40013
#define IDM_HELP                                40014
#define IDM_LABELSET                            40015
#define IDM_VERSION                             40016
#define IDM_LABELADD_ID_START                   40100
#define IDM_LABELDEL_ID_START                   40200
#define IDI_BALLOON                             50000
#define IDI_BOOKMARK_PLUS                       50001
#define IDI_BROWSER                             50002
#define IDI_CROSS                               50003
#define IDI_EXTAPP                              50004
#define IDI_LABEL                               50005
#define IDI_NOTIFY                              50006
#define IDI_PLAY                                50007
#define IDI_SOUND                               50008
#define IDI_TICK                                50009
#define IDI_WRENCH                              50010
#define IDB_POPUPBG                             50100
